### ISSUE TITLE
[Feature Request] Open Teleprompter from a Command + Open as a New Tab

### ISSUE THREAD

**Issue by FelipeRearden** [lumetrium/obsidian-teleprompter#1]
Hello @lumetrium !!!

First of all, I saw your reddit post and I have to says this is AMAZING !!!!!

I have been looking for this feature for a long time ⭐️

I was testing your plugin and I already have 2 FRs to share with you based on the workflow that I wanna use your plugin. 

Let me explain...

## 1️⃣ Option to Open Teleprompter in a New Tab instead of as a Sidebar Item

Since I am gonna use your plugin as a focus reading mode for reading long notes like articles and book notes. 

This way I just wanna a command (from the Command Palette) that opens the Teleprompter (with the content from the Active Note) as a NEW TAB.

Today, to achieve this, I have to drag and drop the Teleprompter from the sidebar to the note workspace every time that I wanna use Teleprompter.

The next FR is related to 1️⃣

## 2️⃣ 2 New Commands : Open Teleprompter using the Command Palette

Today, the only way to open Teleprompter is with mouse clinking on the icon inside the left Ribbon

As a keyboard lover, I just wanna an option to open Teleprompter using my keyboard from a command in the Command Palette.

Based on FR1️⃣ we need 2 two commands:

○ Teleprompter: Open Teleprompter in the Sidebar 
○ Teleprompter: Open Teleprompter in New Tab

This way, we have all scenarios covered :)

---

Thank you for reading this!

Let me know if you need any information!

I wish you a fantastic day ☀️

**Comment by lumetrium** [comment]
Hi! Thank you for your feedback and for such detailed feature requests! I think they are totally justified. It might also be great to include an "Open Teleprompter in a new window" command. I'll put it on the roadmap.

**Comment by FelipeRearden** [comment]
Hello @lumetrium !!!

> Hi! Thank you for your feedback and for such detailed feature requests! I think they are totally justified. 

thank you very much for the reply, I glad to know that you liked my FRs.

> It might also be great to include an "Open Teleprompter in a new window" command.

100% agree! I have missed “new window” :)

> I'll put it on the roadmap.

Thank you !!!!!

**Comment by lumetrium** [comment]
These features have been added in the latest 1.1 release - https://github.com/lumetrium/obsidian-teleprompter/releases/tag/1.1.0
