### ISSUE TITLE
Teleprompter - text wrap/line breaak

### ISSUE THREAD

**Issue by chrisglawley** [lumetrium/obsidian-teleprompter#10]
It'd be very useful if Teleprompter had the ability to reproduce new lines as breaks as well as new paragraphs.
For example:
## Current display...
It's of a flash frigate, La Pique was her name, All in the West Indies she bore a great fame For cruel bad usage of ev'ry degree, Like slaves in a galley we ploughed the salt sea. Derry down, down, Down, derry down.

Now at four in the morning our work does begin, In our 'twixt decks and cockpit a bucket might swim; Our fore and main topmen so loudly do bawl For sand and for holystone both great and small.

---

## Suggested display
It's of a flash frigate, La Pique was her name,
All in the West Indies she bore a great fame
For cruel bad usage of ev'ry degree,
Like slaves in a galley we ploughed the salt sea.
Derry down, down,
Down, derry down.

Now at four in the morning our work does begin,
In our 'twixt decks and cockpit a bucket might swim;
Our fore and main topmen so loudly do bawl
For sand and for holystone both great and small.

---

Fair Winds
chris :-)

**Comment by lumetrium** [comment]
Thanks! I'll make sure to fix this in the upcoming update.

**Comment by chrisglawley** [comment]
I discover that if you use the codeblock syntax from the obsidian columns plugin
(https://github.com/tnichols217/obsidian-columns)
then the expected lin wrap appears !

buuut that's a bit awkward.


I need to find the "buy you a coffee (tea?)" link!
Fair winds
chris :-)

**Comment by lumetrium** [comment]
There's no such link, but I appreciate the intent!

Good to know you've found a temporary workaround. I consider this issue a bug, so I'll be addressing it with priority.
