### ISSUE TITLE
Teleprompter - Open in new window

### ISSUE THREAD

**Issue by chrisglawley** [lumetrium/obsidian-teleprompter#11]
It'd be handy to have tick box option to open in a new window when th TP is started.

I'm new with this (very handy indeed) plugin and realisee there may be a way to do this already but I'suffering User Blindness

Fair winds
chris :-)

**Comment by lumetrium** [comment]
I'm not entirely sure what you're looking for. If you want to open the teleprompter in a new window automatically when the "Play" button is pressed, then unfortunately, such a feature does not currently exist.

However, if you just want to have the teleprompter appear in a separate window, you can use the "Detach window" feature. Here's the demo: 
![detach-window](https://github.com/lumetrium/obsidian-teleprompter/assets/125469344/510c9501-08ff-4310-82cb-6ce8e58def81)


Also, there are several commands for this:
- Teleprompter: Open in new window
- Teleprompter: Detach window - toggle
- Teleprompter: Detach window - toggle on
- Teleprompter: Detach window - toggle off

**Comment by chrisglawley** [comment]
Wow, Stars for swift response !!

You got it. I'm thinking an option in the config such that it always opens in a new window, not from pressing play.

I must play with the command options and set a hot key. I expect that'll do the trick


Fair winds
chris :-)

**Comment by lumetrium** [comment]
I see, thank you for clarifying. Such an option does not exist yet, but it's actually a great idea! I'll add it to the backlog.
