### ISSUE TITLE
Can't update teleprompter plugin

### ISSUE THREAD

**Issue by SergeStinckwich** [lumetrium/obsidian-teleprompter#15]
I try to update teleprompter (currently installed version: 1.2.0) to 1.3.0, but the update does not work. Obsidian tell me that the plugin is installed but this is not the case. Same issue if I remove teleprompter plugin and then reinstall. I'm stuck at 1.2.0.
My Obsidian version is the latest (1.5.12)

**Comment by lumetrium** [comment]
Thanks a lot for reporting this. I've published a fix, and it should be possible to update now. I'm closing this as solved, but if the problem persists and you're unable to update, please feel free to reopen the issue.

**Comment by SergeStinckwich** [comment]
This is working now ! Thank you 🙏
