### ISSUE TITLE
Text in teleprompter does not update when file is changed externally

### ISSUE THREAD

**Issue by derkork** [lumetrium/obsidian-teleprompter#2]
I'm using Obsidian both on a tablet and on a desktop PC. For ease of editing, I tend to make script corrections on the PC. These changes are synchronized over to the tablet with Syncthing. Once they are synchronized they will update inside of Obsidian on the tablet. However if I have a teleprompter open on the tablet, it will not update its contents. So the note will show the new version while the teleprompter shows the old version. I need to close and reopen Obsidian or do a change to the document on the tablet, so the contents are matching up again.

Maybe this is because when synching the file is changed externally.

**Comment by lumetrium** [comment]
Resolved in the [1.1.1 release](https://github.com/lumetrium/obsidian-teleprompter/releases/tag/1.1.1). Thank you for reporting this.

**Comment by derkork** [comment]
Awesome, thank you very much!
