### ISSUE TITLE
Option to turn on an eyeline indicator?

### ISSUE THREAD

**Issue by chrisnorth90** [lumetrium/obsidian-teleprompter#3]
I often shoot video of clients reading from a prompter. Some of the software I've used allows you to put an arrow on screen in the left margin. The arrow doesn't move when the text scrolls; it is locked on screen wherever you leave it. 

Ive found that this arrow is helpful when recording someone else. I'll line up the arrow with the center of the lens and then I'll ride the prompter speed as the talent speaks. The arrow helps me keep the upcoming text centered, and for the reader it helps with maintaining eye contact and keeping track of their place in the script.

I think it would be a neat feature. If it's is too much work to add, don't stress over it.

**Comment by lumetrium** [comment]
Sure, it's already in the plans. It's a common feature for teleprompters and is definitely worth adding. Appreciate you sharing your use-case.

**Comment by mehd-io** [comment]
Hey! I Love the plugin. I started to use it, but I kinda of feel lost without this feature.
The visual cue really helps to assist the reader in maintaining their place in the text and a steady flow. Plus that enables one to have a constant eye focus in a single place

**Comment by lumetrium** [comment]
Added in https://github.com/lumetrium/obsidian-teleprompter/releases/tag/1.2.0

**Comment by mehd-io** [comment]
wow, amazing, thanks @lumetrium !!
