### ISSUE TITLE
countdown before play

### ISSUE THREAD

**Issue by Morglaf** [lumetrium/obsidian-teleprompter#9]
It would be really nice to have a programmable countdown...

**Comment by lumetrium** [comment]
Thanks for the suggestion! It would be helpful if you could describe in more detail how you envision this feature working.

**Comment by Morglaf** [comment]
![obsidian](https://github.com/lumetrium/obsidian-teleprompter/assets/22679426/c3094407-27ae-4c53-a939-05324d14242e)

Hello,
Thank you for your reply.
For me the idea would be to have a button to which I can add seconds (from 1 to 30 seconds I would say) which would allow a pre-roll with, if it's luxurious, a countdown on the screen.
So when the pre-roll is activated, when I press the play button I see the countdown, I sit quietly and then I talk...

**Comment by lumetrium** [comment]
This feature has been added in the latest 1.3.0 release. For more details, see the release notes at https://github.com/lumetrium/obsidian-teleprompter/releases/tag/1.3.0.

![countdown-demo](https://i.imgur.com/BnTu2PF.gif)

Note that you must add the new countdown control to your control panel manually. 

Feel free to share your thoughts on the implementation.

**Comment by Morglaf** [comment]
Thank you very much!
You make my day!
